micronaut:
  application:
    name: pixKeymanager

grpc:
  server:
    port: ${SERVER_PORT}

datasources:
  default:
    url: ${DB_URL}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.format_sql: true
jpa.default.properties.hibernate.show_sql: true

clients:
  itau:
    url: ${ITAU_HOST_URL}
  bcb:
    url: ${BCB_HOST_URL}